### PR TITLE
Change sleep time for main thread before interrupting thr to 2 seconds

### PR DESCRIPTION
**Pull request by sankalpbhatia**
Hi, 
I noticed that the sleep time in the main thread of this project allows enough time for the iterations to complete and hence the other thread terminates before getting interrupted. 
I noticed this in my machine and also on the demo of one of the videos of the LiveLessons training.
The video name is " Understand the Java Thread lifecycle and how to manage it effectively" from Java Concurrency LiveLessons video training. 
This is probably nitpicking but i thought it would be much better if the program runs correctly every time.

Regards,
Sankalp

### CODE REVIEW

**Comment by sankalpbhatia** [comment]
@douglascraigschmidt too late to comment but any updates?

**Comment by douglascraigschmidt** [comment]
Hi Sankalp, can you please send me a push request with the patches that will fix this problem?

Thanks very much,

Doug

**Comment by sankalpbhatia** [comment]
I am sorry I did not understand. I think you can merge this request to the master branch. Is that what you mean't by a push request? Pardon me if this is a silly question. This is my first ever pull request. 

Thanks,
Sankalp

**Comment by douglascraigschmidt** [comment]
Sankalp, I think we're all set now, thanks very much!

Doug

**Comment by sankalpbhatia** [comment]
Glad I could help! Thanks for your time.

**Pull request merged**
